- name: Add APT key
  become: true
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc
    state: present
  tags: install

- name: Add APT repository
  become: true
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
    state: present
  tags: install

- name: Install mongodb package
  become: true
  apt:
    name: mongodb-org
    state: present
  tags: install

- name: Configure service supervisor
  become: true
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install
